### PR TITLE
Updated references to NLog 4.4.1 and Autofac 2.2.4.900

### PR DESCRIPTION
**Pull request by structre40**
Retarget .Net 4.5.2
Modify tests so they pass using ResolveNamed.
Updating deprecated methods

### CODE REVIEW

**Comment by ziyasal** [comment]
hi @structre40  thanks 👍

**Comment by structre40** [comment]
My please. Any chance you will be updating the Nuget package for it?

**Comment by ziyasal** [comment]
@structre40 I have problems with my win box :( right after fixing it I'll push new package asap.

**Comment by structre40** [comment]
Thanks a bunch!

**Pull request merged**
